- hosts: awx
  become: yes 
  user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: 'Atualizando o repo'
    apt:
      update_cache: "yes"
      force_apt_get: "yes"
  roles:
  - { role: instalacao-awx, tags: ["instalacao_awx_role"] }