- name: helm repository prometheus
  shell: helm repo add prometheus-community {{ url_repo_prometheus }}
  register: prometheus_add_repo

- name: helm repository stable
  shell: helm repo add stable {{ url_repo_stable }}
  register: stable_add_repo

- name: helm update 
  shell: helm repo update
  register: prometheus_repo_update

- name: Instalando o Prometheus
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_install  
